name: SparkPlug.Contracts Build

on:
  push:
    paths:
      - 'src/SparkPlug.Contracts/**'
  pull_request:
    paths:
      - 'src/SparkPlug.Contracts/**'

env:
  PROJECT: src/SparkPlug.Contracts/SparkPlug.Contracts.csproj

jobs:
  build:
    name: Build SparkPlug.Contracts App
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]
            dotnet-version: [7.0.x]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore $PROJECT
    - name: Build
      run: dotnet build $PROJECT --no-restore
