name: SparkPlug.Contracts Build

on:
  push:
    paths:
      - 'src/SparkPlug.Contracts/**'
      - 'tests/SparkPlug.Contracts.Test/**'
  pull_request:
    paths:
      - 'src/SparkPlug.Contracts/**'
      - 'tests/SparkPlug.Contracts.Test/**'
  workflow_dispatch:

env:
  PROJECT: ./src/SparkPlug.Contracts/SparkPlug.Contracts.csproj

jobs:
  build:
    name: Build SparkPlug.Contracts App
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]
            dotnet-version: [7.0.x]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT }}
    - name: Build
      run: dotnet build ${{ env.PROJECT }} --no-restore
