name: SonarCloud Analysis

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "main"]
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install Dotnet Coverage tool
        shell: powershell
        run: dotnet tool update --global dotnet-coverage --version 17.4.4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and run tests
        run: dotnet coverage collect "dotnet test" -f xml -o "coverage.xml"

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=natarajan-ganapathi
            -Dsonar.projectKey=natarajanganapathi_sparkplug
            -Dsonar.cs.vscoveragexml.reportsPaths=coverage.xml
            -Dsonar.sources=src/
            -Dsonar.test.exclusions=test/**
            -Dsonar.tests=test/
            -Dsonar.verbose=true