name: Sonar Cloud Analysis (SAST)

on:
  push:
    branches: [ "feature/*" ]
    paths-ignore: ["docfx", "samples", ".github"]
  pull_request:
    branches: [ "main"]
    paths-ignore: ["docfx", "samples", ".github"]
  workflow_dispatch:

jobs:
  sast:
    name: Static Application Security Testing
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: 21

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar-packages
          restore-keys: ${{ runner.os }}-sonar-packages

      - name: Cache SonarQube scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install tools
        shell: powershell
        run: |
          dotnet tool update --global dotnet-sonarscanner  --version 6.1.0
          dotnet tool update --global dotnet-coverage --version 17.4.4

      - name: Run tests and collect coverage
        run: |
          dotnet tool list -g
          dotnet coverage collect "dotnet test" -f xml -o "coverage.xml"

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin `
                /k:"natarajanganapathi_sparkplug" `
                /o:"natarajan-ganapathi" `
                /d:sonar.login="%SONAR_TOKEN%" `
                /d:sonar.cs.vscoveragexml.reportsPaths="coverage.xml" `
                /d:sonar.host.url="https://sonarcloud.io" `
                /d:sonar.tests="tests/" `
                /d:sonar.exclusions="**/samples/**,**/tests/**" `
                /d:sonar.test.exclusions="**/samples/**,**/tests/**" `
                /d:sonar.coverage.exclusions="**/samples/**,**/tests/**"
          dotnet build --no-incremental
          dotnet sonarscanner end /d:sonar.login="%SONAR_TOKEN%"          
          
      # - name: Build and analyze
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   shell: powershell
      #   run: |
      #     dotnet tool list -g
      #     dotnet coverage collect "dotnet test" -f xml -o "coverage.xml"
      #     dotnet sonarscanner begin `
      #           /k:"natarajanganapathi_sparkplug" `
      #           /o:"natarajan-ganapathi" `
      #           /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
      #           /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml `
      #           /d:sonar.host.url="https://sonarcloud.io" `
      #           /d:sonar.tests="tests/" `
      #           /d:sonar.exclusions="**/samples/**,**/tests/**" `
      #           /d:sonar.test.exclusions="**/samples/**,**/tests/**" `
      #           /d:sonar.coverage.exclusions="**/samples/**,**/tests/**"
      #     dotnet build --no-incremental
      #     dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"